### ISSUE TITLE
InlineVerifyer: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Strech** [Shopify/ghostferry#337]
[Shop move](https://app.shopify.com/services/internal/shop_mover/queues/3987406849/progress) cause ghostferry to terminate with panic about memory issue.

Backtrace

```
    /home/runner/work/ghostferry/ghostferry/inline_verifier.go:729 +0x159
github.com/Shopify/ghostferry.(*InlineVerifier).verifyBinlogBatch.func1(0xc00ac91240, 0xc000312300, 0xc000232290, 0x10, 0xc000019230, 0x24, 0xc000867180, 0x3, 0x64, 0xc0004ea910, ...)
    /home/runner/work/ghostferry/ghostferry/utils.go:20
github.com/Shopify/ghostferry.WithRetries(...)
    /home/runner/work/ghostferry/ghostferry/utils.go:39 +0x1d6
github.com/Shopify/ghostferry.WithRetriesContext(0x0, 0x0, 0x5, 0x0, 0xc000b22150, 0x812215, 0x1f, 0xc003adbef8, 0x31, 0x15)
    /home/runner/work/ghostferry/ghostferry/inline_verifier.go:730 +0x9f
github.com/Shopify/ghostferry.(*InlineVerifier).verifyBinlogBatch.func1.1(0x4d34557a4d343453, 0x6a4d222c223d557a)
    /home/runner/work/ghostferry/ghostferry/inline_verifier.go:474 +0xc6
github.com/Shopify/ghostferry.(*InlineVerifier).getFingerprintDataFromSourceDb(0xc000312300, 0xc000232290, 0x10, 0xc000019230, 0x24, 0x0, 0xc0004ea910, 0xc000867180, 0x3, 0x64, ...)
    /home/runner/work/ghostferry/ghostferry/inline_verifier.go:482 +0x85
github.com/Shopify/ghostferry.(*InlineVerifier).getFingerprintDataFromDb(0xc000312300, 0xc00000f068, 0xc000a3f9a0, 0xc000232290, 0x10, 0xc000019230, 0x24, 0x0, 0xc0004ea910, 0xc000867180, ...)
    /home/runner/work/ghostferry/ghostferry/table_schema_cache.go:79 +0x330
github.com/Shopify/ghostferry.(*TableSchema).FingerprintQuery(0xc0004ea910, 0xc000232290, 0x10, 0xc000019230, 0x24, 0x3, 0x0, 0x0)
    /opt/hostedtoolcache/go/1.16.5/x64/src/strings/strings.go:438 +0x325
strings.Join(0xc007c029a0, 0x2, 0x2, 0x8820c4, 0x1, 0xc004fba5f0, 0x4)
    /opt/hostedtoolcache/go/1.16.5/x64/src/strings/builder.go:123
strings.(*Builder).WriteString(...)
goroutine 3050 [running]:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x125 pc=0x46e725]
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by Strech** [comment]
### Context

The error happen when Ghostferry was trying to verify binlog batch and compute the fingerprint of the source database. It is running those computations for both source and target databases as a go-routines and compares results afterwards.

- [`func (v *InlineVerifier) verifyBinlogBatch(batch BinlogVerifyBatch) ([]InlineVerifierMismatches, error)`](https://github.com/Shopify/ghostferry/blob/b3aaacf5d6ce5f14545befc4fe2b06c93e00c04e/inline_verifier.go#L727-L787)
    - [`sourceFingerprints, sourceDecompressedData, err = v.getFingerprintDataFromSourceDb`](https://github.com/Shopify/ghostferry/blob/b3aaacf5d6ce5f14545befc4fe2b06c93e00c04e/inline_verifier.go#L752)

The computation is done by constructing the query to compute MD5 of specific columns and running it against source/target databases.

- [`func (v *InlineVerifier) getFingerprintDataFromDb(db *sql.DB, stmtCache *StmtCache, schemaName, tableName string, tx *sql.Tx, table *TableSchema, paginationKeys []uint64) (map[uint64][]byte, map[uint64]map[string][]byte, error) {`](https://github.com/Shopify/ghostferry/blob/b3aaacf5d6ce5f14545befc4fe2b06c93e00c04e/inline_verifier.go#L491-L547)
    - [`func (t *TableSchema) FingerprintQuery(schemaName, tableName string, numRows int) string {`](https://github.com/Shopify/ghostferry/blob/b3aaacf5d6ce5f14545befc4fe2b06c93e00c04e/table_schema_cache.go#L61-L85)

Accordingly to the backtrace an error happened during the joining of the column names with separator to interpolate it into the resulting [SELECT](https://github.com/Shopify/ghostferry/blob/b3aaacf5d6ce5f14545befc4fe2b06c93e00c04e/table_schema_cache.go#L77-L84) query.

```golang
return fmt.Sprintf(
	"SELECT %s FROM %s%s WHERE %s IN (%s)",
	strings.Join(columnsToSelect, ","),          // <--- backtrace points to this line
	QuotedTableNameFromString(schemaName, tableName),
	forceIndex,
	columnsToSelect[0],
	strings.Repeat("?,", numRows-1)+"?",
)
```

Since all the related functions are protected with typing system and the resulting slice of the columns was successfully constructed while running the code, we may inspect the Go-lang backtrace part of the code which led us to the [`strings.Join`](https://github.com/golang/go/blob/go1.16.5/src/strings/strings.go#L421-L441) function and its internals

- [`func Join(elems []string, sep string) string {`](https://github.com/golang/go/blob/go1.16.5/src/strings/strings.go#L421-L441)
    - [`func (b *Builder) WriteString(s string) (int, error) {`](https://github.com/golang/go/blob/7677616a263e8ded606cc8297cb67ddc667a876e/src/strings/builder.go#L121-L125)

And since the type system of the go doesn't allow us to pass the `nil` anywhere where the type is `string` and because the error happen during the low-level execution of the writing inside the buffer from the slice of already allocated strings and because [Go-lang doesn't tell you was it allocated on a heap or a stack](https://go.dev/doc/faq#stack_or_heap) me and Riccardo comes to a certain conclusion.

### Conclusion

Seems like it was a real memory corruption, when a slice of the strings which was already successfully constructed and allocated, was somehow removed from the memory of the process or become inaccessible/corrupted during the code execution.

### Action items (ideas)

1. **Go-lang version**

The first what comes to our minds was a question - which version of a Go-lang we are running this code? At accordingly to the backtrace it was `1.16.5` when the latest stable version is [`1.19.3`](https://go.dev/dl/). Due to the nature of the error we might consider the version upgrade because such low-level errors sometimes tied to the compiler and its version which has impact on things like Garbage Collector.

2. **Container memory limits**

Another suspicion was the memory itself. We are running in Kubernetes the docker container with a certain memory limits. What if the Go process ate enough memory and its memory was forced to be cleaned or was overtaken by another go-routing? Was it an extreme case when memory wasn't enough? Does our Kubernetes setup optimal for the current use case pattern?

**Comment by Strech** [comment]
In the current setup we run shop-mover as a sub-process and communicate with it via TCP server, Kubernetes setup is set this way

```yaml
- name: shop-mover
  image: gcr.io/shopify-docker-images/apps/production/shopify
  args:
  - shop-mover
  resources:
    requests:
      memory: 3Gi
      cpu: 1
    limits:
      cpu: 1
      memory: 4Gi
```
