### ISSUE TITLE
panic: sync: negative WaitGroup counter in iterative_verifier

### ISSUE THREAD

**Issue by tclh123** [Shopify/ghostferry#76]
```
...
INFO[0271] starting iterative verification in the background  tag=iterative_verifier
INFO[0271] served http request                           method=POST path=/api/actions/verify tag=control_server time="44.141µs"
INFO[0271] starting verification during cutover          tag=iterative_verifier
DEBU[0271] reverifying                                   batches=2 tag=iterative_verifier
DEBU[0271] received pk batch to reverify                 len(pks)=1 table=t1 tag=iterative_verifier
DEBU[0271] received pk batch to reverify                 len(pks)=1 table=t2 tag=iterative_verifier
INFO[0271] cutover verification complete                 tag=iterative_verifier
panic: sync: negative WaitGroup counter

goroutine 6547 [running]:
sync.(*WaitGroup).Add(0xc00029c650, 0xffffffffffffffff)
        /usr/lib/go/src/sync/waitgroup.go:74 +0x137
sync.(*WaitGroup).Done(0xc00029c650)
        /usr/lib/go/src/sync/waitgroup.go:99 +0x34
github.com/Shopify/ghostferry.(*IterativeVerifier).StartInBackground.func1(0xc000314000)
        /home/user1/go/src/github.com/Shopify/ghostferry/iterative_verifier.go:288 +0x117
created by github.com/Shopify/ghostferry.(*IterativeVerifier).StartInBackground
        /home/user1/go/src/github.com/Shopify/ghostferry/iterative_verifier.go:279 +0x1f6
```

**Comment by tclh123** [comment]
It seems https://github.com/Shopify/ghostferry/commit/b14fd14c6878600487cb6d4f47f96ea25c6d1269#diff-f02ffb9491865803e5c8fb0ecf6ef3caR284 introduced this bug.
