### ISSUE TITLE
binlog_streamer get panic: ev.Header.Timestamp = 0

### ISSUE THREAD

**Issue by tclh123** [Shopify/ghostferry#79]
```
DEBU[8766] found 200 rows                                args="[1089172653]" sql="SELECT `id` FROM `db1`.`table1` WHERE `id` > ? ORDER BY `id` LIMIT 200" table=db1.table1 tag=cursor
DEBU[8766] found 200 rows                                args="[1089172906]" sql="SELECT `id` FROM `db1`.`table1` WHERE `id` > ? ORDER BY `id` LIMIT 200" table=db1.table1 tag=cursor
PANI[8766] logpos: 28594 0 *replication.GenericEvent     tag=binlog_streamer
INFO[8766] exiting binlog streamer                       tag=binlog_streamer
[2018/11/16 15:26:51] [info] binlogsyncer.go:163 syncer is closing...
DEBU[8766] found 200 rows                                args="[1089173124]" sql="SELECT `id` FROM `db1`.`table1` WHERE `id` > ? ORDER BY `id` LIMIT 200" table=db1.table1 tag=cursor
DEBU[8766] found 200 rows                                args="[1089173356]" sql="SELECT `id` FROM `db1`.`table1` WHERE `id` > ? ORDER BY `id` LIMIT 200" table=db1.table1 tag=cursor
DEBU[8767] found 200 rows                                args="[1089173568]" sql="SELECT `id` FROM `db1`.`table1` WHERE `id` > ? ORDER BY `id` LIMIT 200" table=db1.table1 tag=cursor
[2018/11/16 15:26:51] [error] binlogstreamer.go:57 close sync with err: sync is been closing...
[2018/11/16 15:26:51] [info] binlogsyncer.go:178 syncer is closed
panic: (*logrus.Entry) (0x8ccd40,0xc000be3b30)
goroutine 42 [running]:
github.com/Shopify/ghostferry/vendor/github.com/sirupsen/logrus.Entry.log(0xc00013a1e0, 0xc0001de4e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/user1/go/src/github.com/Shopify/ghostferry/vendor/github.com/sirupsen/logrus/entry.go:128 +0x5a8
github.com/Shopify/ghostferry/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc00013b090, 0xc000959ca8, 0x1, 0x1)
        /home/user1/go/src/github.com/Shopify/ghostferry/vendor/github.com/sirupsen/logrus/entry.go:173 +0xb2
github.com/Shopify/ghostferry/vendor/github.com/sirupsen/logrus.(*Entry).Panicf(0xc00013b090, 0x8e4a89, 0x10, 0xc0000bdd30, 0x3, 0x3)
        /home/user1/go/src/github.com/Shopify/ghostferry/vendor/github.com/sirupsen/logrus/entry.go:221 +0xed
github.com/Shopify/ghostferry.(*BinlogStreamer).updateLastStreamedPosAndTime(0xc000105ba0, 0xc000c442a0)
        /home/user1/go/src/github.com/Shopify/ghostferry/binlog_streamer.go:211 +0x140
github.com/Shopify/ghostferry.(*BinlogStreamer).Run(0xc000105ba0)
        /home/user1/go/src/github.com/Shopify/ghostferry/binlog_streamer.go:169 +0x356
github.com/Shopify/ghostferry.(*Ferry).Run.func4(0xc000298610, 0xc00015c0c0)
        /home/user1/go/src/github.com/Shopify/ghostferry/ferry.go:339 +0x55
created by github.com/Shopify/ghostferry.(*Ferry).Run
        /home/user1/go/src/github.com/Shopify/ghostferry/ferry.go:336 +0x243
```

**Comment by shuhaowu** [comment]
Fixed in #80.
